/**
 * Core device integration domain types.
 *
 * The domain knows ONLY about the DeviceAdapter contract and neutral
 * `DeviceMeasurement` records. It does NOT know about Bluetooth, Serial, a
 * specific manufacturer or a proprietary protocol — that knowledge lives inside
 * each adapter. This keeps the domain decoupled from hardware/vendor specifics,
 * satisfying the privacy-first and progressive-enhancement goals.
 */

/**
 * Transport used to reach a device. The domain treats it as opaque metadata.
 */
export type DeviceTransport =
  | "bluetooth"
  | "serial";

/**
 * Type of a connected device (by family, not by manufacturer).
 */
export type DeviceType =
  | "glucose"
  | "weight"
  | "bloodPressure"
  | "other";

/**
 * A device discovered / remembered by the application.
 *
 * Only non-sensitive, non-secret metadata is kept. Credentials or pairing
 * secrets are never stored by the registry.
 */
export type Device = {
  /** Stable identifier generated by the registry/adapter. */
  id: string;
  /** Human-friendly device name (e.g. "Glicosímetro"). */
  name: string;
  type: DeviceType;
  transport: DeviceTransport;
  /** Adapter ID that can handle this device (from the DeviceAdapter.id). */
  adapterId: string;
  manufacturer?: string;
  model?: string;
  /** Adapter-level identifier (e.g. Bluetooth MAC / serial port id). */
  nativeId?: string;
  /** When the device was last connected. */
  lastConnectedAt?: string;
  /** When the device was last successfully synced. */
  lastSyncAt?: string;
};

/**
 * Registry record persisted locally for a connected device. It extends the
 * domain `Device` with the owning user so registry queries stay user-scoped.
 */
export type ConnectedDevice = Device & {
  userId: string;
};

/**
 * A normalized, transport-agnostic measurement read from a device.
 *
 * This is the intermediate representation used by the normalization layer
 * before a measurement becomes a domain entity (e.g. a `GlucoseReading`).
 */
export type DeviceMeasurement = {
  /** Measurement family type. */
  type: "glucose" | "weight" | "bloodPressure" | "other";
  value: number;
  unit: string;
  /** ISO 8601 timestamp of when the measurement was taken. */
  measuredAt: string;
  /** Origin metadata used for Data Ownership tracking and deduplication. */
  source: {
    deviceId: string;
    deviceName?: string;
    manufacturer?: string;
    model?: string;
    transport: DeviceTransport;
    adapterId: string;
    /** Reliable native record id, when the device provides one. */
    sourceRecordId?: string;
  };
};

/**
 * Raw, adapter-specific data read from a device, before parsing/normalization.
 */
export type RawDeviceData = {
  /** MIME-ish hint of the raw payload shape (e.g. "application/json", "text/plain"). */
  format: string;
  /** Raw bytes/text coming straight from the device. */
  data: string | Uint8Array;
};

/**
 * A single recorded sync operation outcome for the sync history.
 */
export type SyncHistoryEntry = {
  id: string;
  userId: string;
  deviceId: string;
  deviceName: string;
  /** When the sync happened. */
  syncedAt: string;
  /** How many new records were imported. */
  importedCount: number;
  /** How many records were skipped as duplicates. */
  duplicateCount: number;
  /** How many records failed validation. */
  errorCount: number;
  /** Whether the sync completed successfully. */
  ok: boolean;
  /** Optional user-friendly failure message. */
  message?: string;
};

/**
 * Result of a completed device sync preview or full sync.
 */
export type SyncResult = {
  deviceId: string;
  /** Total raw measurements found on the device. */
  totalRecords: number;
  /** Measurements usable after parsing + validation. */
  newRecords: number;
  /** Measurements skipped as duplicates. */
  duplicateCount: number;
  /** Measurements that failed validation / parsing. */
  errorCount: number;
  /** User-friendly summary message (PT-BR). */
  message: string;
  /** The normalized measurements that would be / were imported. */
  measurements: DeviceMeasurement[];
};
